name: note_vault_frontend
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  path_provider: ^2.0.15
  open_filex: ^4.3.2
  shared_preferences: ^2.3.2
  flutter:
    sdk: flutter
  http: ^1.5.0
  path: ^1.8.3
  file_picker: ^5.2.5
  cupertino_icons: ^1.0.8

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker
      ref: master
    # 👆 Corrected branch name to avoid Git ref error
    # This override bypasses the default_package warning for Windows
    # Safe until pluginClass is added upstream

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # ✅ Added for app icon generation

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png" # ✅ Path to your custom icon

flutter:
  uses-material-design: true

  assets:
    - assets/icon/logo.png # ✅ Ensure this asset is available
    - assets/icon/avatar_placeholder.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700